version: '3.8'

services:
  db:
    image: postgres:11
    container_name: example_db
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5439:5432"